---
title: Innovation Projects
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: http://projects.austintexas.io
markdown: kramdown
permalink: pretty
exclude:
- api
- bin
- circle.yml
- Gemfile
- vendor
